---
version: 2.0

jobs:
  build:
    docker:
      - image: python:2.7
    steps:
      - checkout
      - run:
          name: Dependencies
          command: pip install s3cmd
      - run:
          name: Deploy
          command: |
            if [ "$CIRCLE_BRANCH" != master ]; then
              echo "Using --dry-run for non-master branch ($CIRCLE_BRANCH)"
              S3CMD='s3cmd --dry-run'
            else
              S3CMD='s3cmd'
            fi

            # Check configuration
            [ -n "$AWS_ACCESS_KEY_ID" ]
            [ -n "$AWS_SECRET_ACCESS_KEY" ]

            $S3CMD \
              --acl-public \
              --access_key "$AWS_ACCESS_KEY_ID" \
              --secret_key "$AWS_SECRET_ACCESS_KEY" \
              --delete-removed \
              --no-mime-magic \
              --cf-invalidate \
              --cf-invalidate-default-index \
              sync _site/ s3://brisb.in

# Using workflows just to get access to shared secrets. Silly
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: org-global
